### ISSUE TITLE
Problemas com IA do inimigo

### ISSUE THREAD

**Issue by Zian25** [SynthWare/Projeto01_Beta#1]
**Descreva o problema**
O inimigo não responde a presença do jogador, ignorando e não fazendo nada alem de movimento pré aleatório

**Como reproduzir?**
Passos para reproduzir o problema:
Chegue perto dele.

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.
R: Seguisse o jogador.

**Configurações do aparelho (Complete abaixo):**
(Não necessário para esse caso.)

**Comment by DocTheodore** [comment]
nova atualização corrigiu este bug, e o inimigo voltou a seguir o player
